@GreenPrint.WebApi_HostAddress = https://localhost:7131



GET {{GreenPrint.WebApi_HostAddress}}/user/1?apikey=12345

###

GET {{GreenPrint.WebApi_HostAddress}}/users?apikey=12345

###

POST {{GreenPrint.WebApi_HostAddress}}/item/create?apikey=12345
Content-Type: application/json

{
  "itemName": "Ender 3 Pro",
  "description": "A good cheap 3D Printer",
  "price": 1700.0,
  "categoryId": 1,
}

###

DELETE {{GreenPrint.WebApi_HostAddress}}/user/remove?UserId=2

###

GET {{GreenPrint.WebApi_HostAddress}}/users/GetDeffered


###

GET {{GreenPrint.WebApi_HostAddress}}/items?apikey=12345



###

GET {{GreenPrint.WebApi_HostAddress}}/item/12?apikey=12345